"""
Django settings for djangoProject1 project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0&u1=1^3%52^nig0_n0hy4%pk(1@)q(mo_g2&6y+&3o*q5zn9d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TCC',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoProject1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'STOCK_STORE',        # Nome do banco de dados MySQL
        'USER': 'root',          # Usuário do MySQL
        'PASSWORD': 'Admin@801',        # Senha do MySQL
        'HOST': 'localhost',            # ou IP do seu servidor MySQL
        'PORT': '3306',                 # Porta padrão do MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


USE_I18N = True

# settings.py
TIME_ZONE = 'America/Sao_Paulo'  # Ou o fuso horário local correto
USE_TZ = True  # Habilite o uso de fuso horário


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Configuração do backend para envio de e-mail no Django.
# Aqui estamos usando o backend padrão do Django para SMTP, que se comunica com o servidor de e-mail.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Nome do host do servidor SMTP. Como estamos usando o Gmail, usamos 'smtp.gmail.com'.
EMAIL_HOST = 'smtp.gmail.com'

# Porta do servidor SMTP para comunicação segura. A porta 587 é usada para SMTP com STARTTLS.
EMAIL_PORT = 587

# Indica se devemos usar TLS (Transport Layer Security) para segurança durante a comunicação.
# TLS é um protocolo de criptografia que protege a transferência de dados.
EMAIL_USE_TLS = True


EMAIL_HOST_USER = 'estoquestockstore@gmail.com'

EMAIL_HOST_PASSWORD = 'hcry egss zzbb izik'


