# Generated by Django 5.1.1 on 2024-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
