# Generated by Django 5.1.1 on 2024-10-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0004_alter_produto_categoria_movimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='quantidade_movimentada',
            new_name='quantidade',
        ),
    ]
