# Generated by Django 5.1.1 on 2024-10-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0005_rename_quantidade_movimentada_movimentacao_quantidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
