# Generated by Django 5.1.1 on 2024-10-22 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0006_delete_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.CharField(choices=[('escritorio', 'Escritório'), ('limpeza', 'Limpeza'), ('eletronicos', 'Eletrônicos'), ('materiais', 'Materiais')], default='escritorio', max_length=20)),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
