# Generated by Django 5.1.2 on 2024-10-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0008_remove_pedidopendente_confirmado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
