# Generated by Django 5.1.2 on 2024-10-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0010_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
