# Generated by Django 5.1.2 on 2024-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0011_funcionario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
