# Generated by Django 5.1.2 on 2024-10-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0013_alter_funcionario_options_alter_funcionario_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
