# Generated by Django 5.1.2 on 2024-10-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0015_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('servicos', models.TextField()),
            ],
        ),
    ]
