# Generated by Django 5.1.2 on 2024-10-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0016_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fornecedores/'),
        ),
    ]
