# Generated by Django 5.1.2 on 2024-10-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0017_fornecedor_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
