# Generated by Django 5.1.2 on 2024-10-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0018_alter_fornecedor_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoPendente',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TCC.fornecedor'),
        ),
    ]
