# Generated by Django 5.1.2 on 2024-10-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0020_funcionario_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='firstname',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='password',
            new_name='Senha',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='lastname',
            new_name='Sobrenome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='phone',
            new_name='Telefone',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='username',
            new_name='Usuário',
        ),
    ]
