# Generated by Django 5.1.2 on 2024-10-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0021_rename_email_funcionario_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Nome',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Sobrenome',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Telefone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Usuário',
            new_name='username',
        ),
    ]
