# Generated by Django 5.1.2 on 2024-10-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0025_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
    ]
