# Generated by Django 5.1.2 on 2024-10-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0025_alter_funcionario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='imagem',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
