# Generated by Django 5.1.2 on 2024-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0026_remove_fornecedor_imagem_fornecedor_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='photo',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fornecedores/'),
        ),
    ]
