# Generated by Django 5.1.2 on 2024-10-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0026_remove_funcionario_user'),
        ('TCC', '0027_remove_fornecedor_photo_fornecedor_foto'),
    ]

    operations = [
    ]
