# Generated by Django 5.1.2 on 2024-11-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0029_mensagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
