# Generated by Django 5.1.2 on 2024-11-06 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0032_remove_pedido_confirmado_remove_pedido_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRemocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('confirmado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCC.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
