# Generated by Django 5.1.2 on 2024-11-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0034_pedido_delete_pedidoremocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='solicitante',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
