# Generated by Django 5.1.2 on 2024-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0035_pedido_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Recusado', 'Recusado')], default='Pendente', max_length=50),
        ),
    ]
