# Generated by Django 5.1.2 on 2024-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0040_alter_fornecedor_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='foto_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
