# Generated by Django 5.1.2 on 2024-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCC', '0043_alter_fornecedor_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
